server:
  port: 8911
spring:
  application:
    name: oauth
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8880/eureka/
    instance:
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
#security:
#  oauth2:
#    client:
#      clientId: paascloud-client-gateway
#      clientSecret: paascloudClientSecret
#      access-token-uri: http://service-zuul:8888/api-a/oauth/token
#      user-authorization-uri: http://service-zuul:8888/api-a/oauth/authorize
#    resource:
#      user-info-uri: http://service-feign:8885/user
#      prefer-token-info: false
#      jwt:
#        key-uri: http://service-feign:8885/oauth/token_key
#proxy:
#  auth:
#    routes:
#      uac-route: oauth2
#      mdc-route: oauth2