server:
  port: ${paascloud.server.provider.uac.port:8888}
spring:
  application:
     name: service-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8880/eureka/
    instance:
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-feign
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000
    api-b:
      path: /api-b/**
      serviceId: service-feign-new
    api-c:
      path: /api-c/**
      serviceId: service-feign-new2
